Solicitud de Hunter
achuhunter/strydercur pull request #1
Opened 2022-04-28 03:22 UTC by achusuperlocotote

### Modificaciones
No seas culero

### Adiciones 
Aplicando a la legion del mal

2022-04-28 03:28 UTC, achusuperlocotote reviewed
Bienvenido

2022-04-28 03:28 UTC, achusuperlocotote commented on aspirantes/fernando.md
> +no seas mierda culero
no soy tan mierda si te acepto

2022-04-28 03:28 UTC, achusuperlocotote commented on aspirantes/fernando.md
> -Por favor acéptame en la legion del mal
ok banda

2022-04-28 03:31 UTC, achuhunter requested changes
Alomejor si te acepto

2022-04-28 03:31 UTC, achuhunter commented on aspirantes/fernando.md
> -Por favor acéptame en la legion del mal
lo voy a pensar

2022-04-28 03:31 UTC, achuhunter commented on aspirantes/fernando.md
> +no seas mierda culero
no soy mierda

2022-04-29 02:36 UTC, achuhunter approved these changes
me parece bien que ayas agregado a kukun

2022-04-29 02:40 UTC, merged